#spring:
#  application:
#    name: config-client
#server:
#  port: 13000
#
#management:
#  endpoints:
#    web:
#      exposure:
#        include: refresh
spring:
  application:
    name: config-client
cloud:
  bus:
    trace:
      enabled: true
    enabled: true

server:
  port: 13000