server:
  port: 9001

spring:
  application:
    name: eureka-consumer-feign-hystrix

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:7000/eureka/

#开启断路器
feign:
  hystrix:
    enabled: true

#增加监控
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream
