spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/guanjian20044/micro-service # 配置git仓库的地址
          search-paths: config-repo # git仓库地址下的相对地址，可以配置多个，用,分割。
#          spring.cloud.config.server.git.username：访问 Git 仓库的用户名
#          spring.cloud.config.server.git.password：访问 Git 仓库的用户密码
server:
  port: 12000